[workspace]
members = ["rustlib",
           "rustlib/maths",
           "rustlib/uselib",
           "rust-stat-dyn",
           #"rust-stat-dyn/dynamic_dispatch",
           #"rust-stat-dyn/static_dispatch",
           "size-of-struct-enum"
    # ... add more crate paths as needed 
    ]
resolver = "2"
